/* Autogenerated by png2wx.pl on Sat Jun  4 21:24:25 2016 */
#ifndef TOOL_ICON
#define TOOL_ICON 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_att;

#endif /* TOOL_ICON */
